### ISSUE TITLE
Fix region coordinates to not include bedrock wall

### ISSUE THREAD

**Issue by Dehyssel** [MineInAbyss/DeeperWorld#57] opened 2021-04-08 04:10 UTC
**Describe the bug**
In L4S1 you can break the bedrock of L4S2, and maybe this applies to all sections.
(Possibility of breaking the bedrock of one section from another)

**To Reproduce**
1. Go to (for example) a bedrock wall in L4S1.
2. Go to the bottom of that section, the game does not let you go to L4S2.
3. Go to the opposite side of the wall, on some point the game will let you go to L4S2 if you go down.
4. In L4S2 you can see that at some point the bedrock broke.

**Expected behavior**
The bedrock wall should be somehow "in sync" with the one in the previous section.

**Screenshots**
For context, the sand is where the bedrock wall is on L4S2.
![2021-04-08_06 01 16](https://user-images.githubusercontent.com/82132658/113966768-02eef900-9830-11eb-8943-872f0408d4b6.png)

If you break these sand blocks and then go to L4S2, the bedrock wall on L4S2 will be also breaked like this.
![2021-04-08_06 04 55](https://user-images.githubusercontent.com/82132658/113967006-6bd67100-9830-11eb-9820-73058506b4f3.png)

You can also see the blocks that players placed on L4S1, but out of the world.
![2021-04-08_06 06 11](https://user-images.githubusercontent.com/82132658/113967149-b5bf5700-9830-11eb-9987-3a65f26bf24c.png)

And if you do /dw linfo in the edge of the bedrock it says this.
![2021-04-08_06 08 32](https://user-images.githubusercontent.com/82132658/113967292-f7500200-9830-11eb-9ac0-03f29c42f91f.png)

**Additional context**
It seems like the bedrock wall of L4S1 and L4S2 aren't in the same position and breaking the block that corresponds to the bedrock block of L4S2, will cause this block to break.

**Comment by 0ffz** [comment] 2021-04-11 22:14
This is caused by the bedrock being considered within the section and getting synced. We can fix this by double-checking all the region bounds to make sure they don't include those walls.

I wanted to suggest ignoring syncing blocks like bedrock but this would cause issues on build, where someone might place/remove bedrock and expect it to be synced.

**Comment by Boy0000** [comment] 2021-04-16 07:56
@0ffz I am curious about your thoughts on assigning this to me :pepehmm:

**Comment by Boy0000** [comment] 2021-04-16 09:16
Should be fixed now. About half of the sections were considering the bedrockwalls part of the section

**Closed by Boy0000** 2021-04-16 09:16 UTC
